export const PRODUCT_REQUEST="PRODUCT_REQUEST"
export const PRODUCT_FAILURE="PRODUCT_FAILURE"

export const ADD_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_MY_ALL_PRODUCTS_SUCCESS="GET_MY_ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_SUCCESS="ALL_PRODUCTS_SUCCESS"

export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"