export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_FAILURE = "AUTH_FAILURE";


//Post 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";


//Get
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const GET_ALL_USERS = "GET_ALL_USERS"

export const LOGINED_USER="LOGINED_USER"

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"

